apiVersion: v1
kind: Pod
metadata: 
  name: pod-2
  labels:
    app: app1
spec:
  volumes:
  - name: pod2-volume
    persistentVolumeClaim:
      claimName: pvc2
  containers:
  - name: pvc2-pod
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html/
      name: pod2-volume
