apiVersion: v1
kind: PersistentVolume
metadata:
  name: first-pv
  labels:
    app: application
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data/"
