apiVersion: v1
kind: Pod
metadata:
  name: pvc1-pod
spec:
  volumes:
  - name: pvc1-pod-storage
    persistentVolumeClaim: 
      claimName: first-pvc
  containers:
  - name : pvc1-container
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /user/share/nginx/html
      name: pvc1-pod-storage

