apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: first-pvc
spec:
  selector:
    matchLabels:
      app: application
  storageClassName: manual
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
