apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc2
spec:
  storageClassName: manual

  selector:
    matchLabels:
      app: app1
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
